#!/bin/bash

# Railway Deployment Helper Script
# This script helps set up environment variables for Railway deployment

set -e

echo "🚀 Railway Deployment Helper"
echo "============================"

# Check if we're in the right directory
if [ ! -f "railway.json" ]; then
    echo "❌ Error: railway.json not found. Run this script from the project root."
    exit 1
fi

echo "📋 Environment Variables for Railway Backend:"
echo "============================================="
echo ""
echo "Add these to your Railway backend project variables:"
echo ""
echo "# AWS Configuration"
echo "AWS_REGION=us-east-1"
echo "AWS_BUCKET_NAME=your-s3-bucket-name"
echo "AWS_ACCESS_KEY_ID=your-aws-access-key"
echo "AWS_SECRET_ACCESS_KEY=your-aws-secret-key"
echo ""
echo "# DynamoDB"
echo "DYNAMODB_TABLE_NAME=easy-video-share-video-metadata"
echo ""
echo "# Redis Configuration (if using Railway Redis plugin)"
echo "REDIS_HOST=your-redis-host"
echo "REDIS_PORT=your-redis-port"
echo "REDIS_PASSWORD=your-redis-password"
echo ""
echo "# Or use external Redis service"
echo "REDIS_URL=redis://your-redis-url:6379/0"
echo ""
echo "# Google AI (optional)"
echo "GOOGLE_CLOUD_PROJECT=your-google-project"
echo "GOOGLE_CLOUD_LOCATION=us-central1"
echo ""
echo "# Railway-specific (Railway sets these automatically)"
echo "RAILWAY_ENVIRONMENT=production"
echo "PORT=8000"
echo ""

echo "📋 Environment Variables for Railway Frontend:"
echo "=============================================="
echo ""
echo "Add these to your Railway frontend project variables:"
echo ""
echo "# Railway Backend URL (get this from your backend deployment)"
echo "VITE_AI_VIDEO_BACKEND_URL=https://your-backend-service.railway.app"
echo ""
echo "# AWS Configuration"
echo "VITE_AWS_REGION=us-east-1"
echo "VITE_AWS_BUCKET_NAME=your-s3-bucket-name"
echo "VITE_AWS_ACCESS_KEY_ID=your-aws-access-key"
echo "VITE_AWS_SECRET_ACCESS_KEY=your-aws-secret-key"
echo ""
echo "# Cognito Configuration"
echo "VITE_COGNITO_REGION=us-east-1"
echo "VITE_COGNITO_USER_POOL_ID=your-user-pool-id"
echo "VITE_COGNITO_CLIENT_ID=your-client-id"
echo ""
echo "# Railway-specific"
echo "VITE_RAILWAY_ENVIRONMENT=production"
echo "VITE_RAILWAY_STATIC_URL=https://your-frontend-service.railway.app"
echo ""

echo "🔧 Deployment Steps:"
echo "==================="
echo ""
echo "1. Deploy Backend:"
echo "   - Create new Railway project"
echo "   - Set source directory to 'backend'"
echo "   - Add environment variables above"
echo "   - Deploy and note the URL"
echo ""
echo "2. Set up Redis:"
echo "   - Add Railway Redis plugin to backend project"
echo "   - Or use external Redis service (Upstash, etc.)"
echo ""
echo "3. Deploy Frontend:"
echo "   - Create new Railway project"
echo "   - Set source directory to '.' (root)"
echo "   - Add environment variables above"
echo "   - Update VITE_AI_VIDEO_BACKEND_URL with backend URL"
echo "   - Deploy"
echo ""
echo "4. Test:"
echo "   - Check backend health: curl https://your-backend.railway.app/health"
echo "   - Test video upload in frontend"
echo ""

echo "✅ Setup complete! Follow the steps above to deploy." 